[package]
name = "spellbook"
description = "A lightweight, Hunspell-like spell checking library"
version = "0.1.0"
authors = ["Michael Davis <mcarsondavis@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
rust-version = "1.65"

[dependencies]
hashbrown = { version = "0.14", default-features = false, features = ["raw"] }
# TODO: move ahash to a dev dependency and allow any hasher?
ahash = { version = "0.8", default-features = false }
