[package]
name = "spellbook"
version = "0.1.0"
authors = ["Michael Davis <mcarsondavis@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
rust-version = "1.60"

[dependencies]
# TODO: investigate using smartstring to cut down on allocations since
# there are plenty of small strings.
