[package]
name = "spellbook"
description = "A lightweight, Hunspell-like spell checking library"
version = "0.1.0"
authors = ["Michael Davis <mcarsondavis@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
rust-version = "1.60"

[dependencies]
