[package]
name = "spellbook"
description = "A lightweight, Hunspell-like spell checking library"
version = "0.1.0"
authors = ["Michael Davis <mcarsondavis@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
rust-version = "1.65"

[dependencies]
hashbrown = { version = "0.14", default-features = false, features = ["raw"] }

[dev-dependencies]
# Used as a BuildHasher for the hashing data types - hashbrown HashMap and a custom
# `HashMultiMap` - during unit tests.
ahash = { version = "0.8", default-features = false }
# Used in unit tests to prevent compiling the same dictionary twice. Used instead of
# `core::cell::OnceCell` since it implements `Send + Sync`.
once_cell = "1.19"
# Used in the integration tests to find and read Hunspell test case files, potentially
# with odd encodings.
glob = "0.3"
encoding_rs = "0.8"
chardetng = "0.1"
